### ISSUE TITLE
Handling password of imported database users

### ISSUE THREAD

**Issue by IljaN** [owncloud/data_exporter#26]
If a database user is imported the password from the old instance can't be reused. In this case we set a random password and trigger an account activation email for the user to set a new password.

If the backend is LDAP then nothing is done and the user from LDAP is reused.

**Comment by micbar** [comment]
@PVince81 the problem is, that we have stored a hashed password. We have no API to write a hashed password to the DB. `$user->setPassword($password, $recoveryPassword)` only takes a clear text password.

We were discussing two options:
1) Write the password to the DB directly, which would break the concept of only using APIs for this app
2) Extend Core to accept hashed password for the DB User Backend.

**Comment by PVince81** [comment]
> 1md because I don't know if it is easily possible to (re)send account activation mails.

@sharidas might know. this falls under "password forgotten" part but might need a custom message.

**Comment by IljaN** [comment]
So we will go the route of writing the password in the database via sql during import as the latest exporter version for owncloud is maintained thus can use the database directly.

This also needs to be handled by ocis importer.
