### ISSUE TITLE
Create Test Suite for OC9 / PHP 5.6 - Exporter only

### ISSUE THREAD

**Issue by micbar** [owncloud/data_exporter#94]
## Description

Create a separate unit/integration test suite for ownCloud 9 and php5.6 for the exporter part only.

## Background
We support the export for ownCloud 9.

**Comment by individual-it** [comment]
blocked by https://github.com/owncloud-ci/core/issues/17

**Comment by individual-it** [comment]
tried to achieve the task by building images of owncloud-ci/co with php 5.6 https://github.com/owncloud-ci/core/pull/20
and then run the tests with that https://github.com/owncloud/data_exporter/pull/101
Next problem is that the testing app does not work with oC 9
So tried to adjust that: https://github.com/owncloud/testing/pull/111
But it does not work because of occ commands behaving differently

It might be possible to make it run but I guess I will have to go into a couple of :rabbit2: :hole: 

@patrickjahns @PVince81 how much more time to invest into this?

**Comment by felixboehm** [comment]
please stop oc9 testing, needs testing on demand.
closed
